CREATE TABLE t1(A INT NOT NULL PRIMARY KEY);
CREATE TABLE t2(B INT NOT NULL REFERENCES t1(A));
INSERT INTO t1(A)VALUES(1);
INSERT INTO t1(A) VALUES(2);
SELECT * FROM t1;
SELECT * FROM t2;
SELECT @@TRANCOUNT --0
BEGIN TRAN;
SELECT @@TRANCOUNT --1
INSERT INTO t2(B) values(1);
INSERT INTO t2(B) values(3);
INSERT INTO t2(B) values(2);
COMMIT TRAN
SELECT @@TRANCOUNT --0
SELECT * FROM t1;
SELECT * FROM t2;

CREATE TABLE ACCOUNT
(id INT  PRIMARY KEY,
amount INT NOT NULL,
Name VARCHAR(30) NOT NULL,
CONSTRAINT CHK_USERR CHECK (amount >=0)
);
INSERT INTO ACCOUNT
VALUES
(1,192,'Dorina'),
(2,20000,'Alex'),
(3, 22223,'Maria');
--DEADLOCK
--SESSION1
BEGIN TRAN;
UPDATE ACCOUNT
SET amount=200
WHERE ID=1;
 

 UPDATE ACCOUNT
SET amount=199920
WHERE ID=2;

COMMIT TRAN

--commited
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRAN;
SELECT * FROM ACCOUNT;
INSERT INTO ACCOUNT
VALUES
(121112,192,'Maria');
ROLLBACK
Commit
--------------------------
--READ UNCOMMITED ::DIRTYREAD
BEGIN TRAN;
SELECT * FROM ACCOUNT;
INSERT INTO ACCOUNT
VALUES
(121112,192,'Dorina');

INSERT INTO ACCOUNT
VALUES
(2115,11402,'LAU');
ROLLBACK
SELECT*FROM ACCOUNT
ROLLBACK;
-------------------
--NON-REPEATABLE READ
BEGIN TRAN;
SELECT*FROM ACCOUNT
 UPDATE ACCOUNT
SET amount=0
WHERE ID=2;
--we put exclusive,at update
INSERT INTO ACCOUNT
VALUES
(210015,11402,'LAU');
SELECT *FROM ACCOUNT;
ROLLBACK;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
----------
--repetable reads --Phantom Read
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
SELECT *FROM ACCOUNT;
SELECT *FROM ACCOUNT;
COMMIT
rollback
